language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: purplediane
  password:
    secure: AE6l3DlnBE6PrLZHUdUgwDAqFxGFAt6bePqR1N1mNWuZ5wc5+a3l4G290f53vQN0i9yWUJuJLgvdFdXYzxGkmGv1xsfwPZH05lH4n1LUA2YvUy1ezW9JBnEdGXFw1grC1JLLWSvNEeaE+18IvAlk8kFuoUU1vtGyfaW/7FPlrF4gzq/k7+91L4sAdwQQfW2jynBK1SgVtHcFSSS81YV7ot++45VHMsdD+ZEpMpYHEinr+E8mx7oB6PMI+E0ztKnKciArU1w3nJbmMIYFaklQwbEG4ocqWufiJducY8Qz/tjWSXWZa3ZHp62eIxdZf8WavWvTtuIYxm98Ga4vW9+AwhrPnEQdSdeIEdCRV3yxcJa2J3/fNjhIRSBhYey9YMW1oWfImpEEv1EdXMmyLoAUWM6pzJ3H8HVdsIPsohpEihAruCS5xPUjuzlLr9peFCP4tUWGQdCB1guaixrTchWh7ZrG2Vz04q0l04SVJcpDlQ4t7sQKsOIpXcDMhTcSEhi/GZauuHlkm4m+kfitAcQxg2qJPFfa70P0iJpiAq8U6Aj65UuFsgfKR8rpSjczjjAGSpUL6Vl+Ma0PaIYB9GC4gBlztXyUtc/32zSrpR2NKrxdC3aNyUvt5FohZXU+272feNEpoCZ1ptlRVvn/2U2OGb/CtoGpd/Gt5wv1sNKQOQs=
  on:
    tags: true
    repo: purplediane/shortbread
    python: 3.6
